- hosts: localhost
  vars:
    source_ssh_dir: "./.ssh"
    dest_ssh_dir: "{{ lookup('env', 'HOME') }}/.ssh"
    Projects: "{{ lookup('env', 'HOME') }}/Projects"
    username: "alan"
    go_url: "https://go.dev/dl/go1.19.linux-amd64.tar.gz"
    solc_url: "https://github.com/ethereum/solidity/releases/download/v0.8.16/solc-static-linux"
  pre_tasks:
  - name: Update Dnf
    become: true
    dnf:
      update_cache: true
      state: present
    tags:
      - install
      - core
  tasks:
    - import_tasks: tasks/ssh.yml
    - import_tasks: tasks/core-setup.yml
    - import_tasks: tasks/git-setup.yml
    - import_tasks: tasks/dev-setup.yml
    - import_tasks: tasks/dotfiles.yml
    - import_tasks: tasks/brave.yml
    - import_tasks: tasks/fonts.yml
    - import_tasks: tasks/nvim-setup.yml
    - import_tasks: tasks/lsp-setup.yml
