- name: Install Packages 1 (Developer tools, Developer libraries etc)
  become: true
  dnf:
    name: [ "@Development Tools", "@Development Libraries", "ninja-build", "libtool", "autoconf", "automake", "cmake", "gcc", "gcc-c++", "make", "pkgconfig", "unzip", "patch", "gettext", "curl", "lua" ]
    allowerasing: true
  tags:
    - install
    - core
    - neovim

- name: Install Packages 2 (dnf-plugins-core)
  become: true
  dnf:
    name: [ "dnf-plugins-core", "util-linux-user" ]
  tags:
    - install
    - core
    - docker
    - brave

- name: Install RPM Fusion
  become: true
  shell:  dnf install https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm -y
  tags:
    - install
    - core
    - rpm-fusion
