- name: Install Gopls
  shell: go install golang.org/x/tools/gopls@latest
  environment:
    GOROOT: "/usr/local/go"
    GOPATH: "{{ ansible_env.HOME }}/Projects/go"
    PATH: "{{ ansible_env.PATH }}:/usr/local/go/bin"
  tags:
    - install
    - go
    - lsp

- name: Install Typescript server
  become: true
  npm:
    name: typescript-language-server
    global: yes
  tags:
    - install
    - node
    - lsp

- name: Install Bash server
  become: true
  npm:
    name: bash-language-server
    global: yes
  tags:
    - install
    - lsp
