- name: Remove neovim
  shell: rm -rf ~/Projects/neovim
  tags:
    - install
    - neovim

- name: Clone Neovim
  ansible.builtin.git:
    repo: 'https://github.com/neovim/neovim.git'
    dest: "{{ lookup('env', 'HOME') }}/Projects/neovim"
  tags:
    - install
    - neovim

- name: Build neovim
  shell: "cd {{ lookup('env', 'HOME') }}/Projects/neovim && make -j 20"
  tags:
    - install
    - neovim

- name: Install neovim
  become: true
  shell: "cd {{ lookup('env', 'HOME') }}/Projects/neovim && make install"
  tags:
    - install
    - neovim

- name: Neovim Plugin Development 1
  become: true
  dnf:
    name: [ "luarocks", "lua-devel" ]
  tags:
    - install
    - neovim

- name: Neovim Plugin Development 2 luacheck
  become: true
  shell: luarocks install luacheck
  tags:
    - install
    - neovim

- name: Install packer.nvim
  ansible.builtin.git:
    repo: 'https://github.com/wbthomason/packer.nvim'
    dest: "{{ lookup('env', 'HOME') }}/.local/share/nvim/site/pack/packer/start/packer.nvim"
    depth: 1
  tags:
    - packer
    - neovim
