- name: Ensure .ssh directory exists.
  file:
    dest: "{{ dest_ssh_dir }}"
    mode: 0700
    state: directory
  tags:
    - dotfiles
    - install
    - ssh

- name: Install ssh private key
  copy:
    src: "{{ source_ssh_dir }}/id_rsa"
    dest: "{{ dest_ssh_dir }}/id_rsa"
    mode: 0600
  tags:
    - dotfiles
    - install
    - ssh

- name: Install ssh public key
  copy:
    src: "{{ source_ssh_dir }}/id_rsa.pub"
    dest: "{{ dest_ssh_dir }}/id_rsa.pub"
    mode: 0644
  tags:
    - dotfiles
    - install
    - ssh

- name: Install ssh config
  copy:
    src: "{{ source_ssh_dir }}/config"
    dest: "{{ dest_ssh_dir }}/config"
    mode: 0644
  tags:
    - dotfiles
    - install
    - ssh
